describe('sign up', () => {
  it('sign up, login as new user, see dialog', () => {
    cy.visit('signup')
    cy.get('#firstName')
      .type('Mike')
    cy.get('#lastName')
      .type('C')
    cy.get('#username')
      .type(Date.now())
    cy.get('#password')
      .type('password')
    cy.get('#confirmPassword')
      .type('password')
    cy.contains('button', 'Sign Up')
      .click()
    cy.get('#username')
      .type('MikeC')
    cy.get('#password')
      .type('password')
    cy.contains('button', 'Sign In')
      .click()
    cy.url()
      .should('equal', 'http://localhost:3000/')
    cy.contains('[role=dialog]', 'Get Started with Real World App')
      .should('be.visible')
  })
})