describe('sign up', () => {
  it('sign up, login as new user', () => {
    cy.visit('signup')
    cy.get('#firstName')
      .type('Mike')
    cy.get('#lastName')
      .type('C')
    cy.get('#username')
      .type('MikeC')
    cy.get('#password')
      .type('password')
    cy.get('#confirmPassword')
      .type('password')
    cy.contains('button', 'Sign Up')
      .click()
    cy.get('#username')
      .type('MikeC')
    cy.get('#password')
      .type('password')
    cy.contains('button', 'Sign In')
      .click()
  })
})